### ISSUE TITLE
Package not working before publishing config and views

### ISSUE THREAD

**Issue by adevade** [olliecodes/laravel-etched-blade#9] opened 2021-06-29 15:26 UTC
Interesting package! Trying it out on a smaller project. Found some bugs:

After I required the package and added a `@etched` block in a view, I got the following error: 
`InvalidArgumentException: No theme found for 'simple'`.

Tried publishing the config file by copying the command from the readme: 
`php artisan vendor:publish --provider="\OllieCodes\Etched\EtchedServiceProvider" --tag=config` 
and got the following error: `Unable to locate publishable resources.`
It worked when I removed the leading slash in the namespace.

Then I reloaded the page and got another error: `InvalidArgumentException: View [themes.simple.blocks.code-indented] not found.`

I couldn't publish the views with or without the leading slash in the namespace.

I think they are not included in the downloaded package because of `/resources/ export-ignore` in `.gitattributes`. 

-----

I'll see if I can submit a PR later. Thanks for you work!

**Comment by ollieread** [comment] 2021-07-01 13:56
@adevade which version are you using? This was an annoying bug in the initial version that I have since fixed.

**Comment by ollieread** [comment] 2021-07-01 14:09
@adevade I've merged in your PR and released v1.0.3, can you confirm that this is still the case?

**Comment by ollieread** [comment] 2021-07-01 14:14
@adevade ah, apologies for the spam, but I have solved the problem. The issue is the `\` at the start of the provider namespace ~_~, will update the readme accordingly.

**Closed as completed** 2021-07-01 14:14 UTC
Labels: bug

**Comment by ollieread** [comment] 2021-07-01 14:23
@adevade There were a handful of issues present here. The first was the `\` at the start of the namespace in the commands, my bad, I've fixed that in the README. The second was that I wasn't actually registering the views as publishable assets. This has since been fixed.
